name="data science with python"
print(name);
print("name=",name);
print(name[5]);
print(name[-1]);
print(name[-2]);
print(name.upper());
print(name.lower());
print(name.title());
print(name[2:5]);
print(name[5:-2]);
print(name.capitalize());
print(name.isalnum());
print(name.isalpha());
print(name.isascii());
print(name.isdigit());
print(name.isdecimal());
print(name.islower());
print(name.isnumeric());
print(name.isprintable());
print(name.isspace());
print(name.istitle());
print(name.isupper());
print(name.islower());
print(name.find('with'));
print(name.find('a'));
print(name.find('l'));
s1='hello'
s2='world'
print(s1+s2);
str='rgukt'
print(str.upper());
print(str);
